### ISSUE TITLE
Add commands to the admin-group

### ISSUE THREAD

**Issue by ePfirsich** [chrism431/TelegramGroupAntiSpamBot#1]
Add group to the Bot (Bot has to be admin in teh group before):
/addgroup [URL]

Remove group from the bot:
/removegroup [URL]

Add blacklist entry:
/addkeyword [wort]

Remove blacklist entry:
/removekeyword [wort]

**Comment by chrism431** [comment]
/addkeyword
Show blacklist

/addkeyword word1 word2 ...
Add entries to blacklist

/removekeyword
Show blacklist
/removekeyword word1 word2 ...
Remove entries from blacklist

**Comment by chrism431** [comment]
/addgroup
Show all group IDs

/addgroup 123 -123
Add groups to monitored groups (space separated)

/removegroup
Show all group IDS

/removegroup 123 -123
Remove groups from monitored groups (space separated)
